name: Bazel

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1

      - name: Build
        run: |
          cd uCShell
          ls
          bazel build //main:uCShell-bin
