name: Bazel

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1

      - name: Build
        run: |
          bazel build //main:uCShell-bin
#the above commands are a workaround because i dont know how to get github actions
#to also check out my submodule
